# primary
version: '3'
services:
  nginx:
    image: nginx
    restart: always
    volumes:
      # static content
      - ../volumes/nginx/www:/www:ro
      # config
      - ../volumes/nginx/config:/etc/nginx/conf.d:ro
      # ssl
      - ../volumes/certbot/etc:/etc/letsencrypt:ro
      # - ../volumes/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
