# primary
version: '3'
#name: nginx
services:
  nginx:
    image: nginx
    volumes:
      # static content
      - ../volumes/nginx/www:/www:ro
      # config
      - ../volumes/nginx/config:/etc/nginx/conf.d:ro
      # ssl
      - ../volumes/certbot/etc:/etc/letsencrypt:ro
      # - ../volumes/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    #networks:
    #  - nginx-main
