version: '3'
#name: nginx
services:
  nginx:
    image: nginx
    volumes:
      # static content
      - ../volumes/www:/www:ro
      # config
      - ../volumes/nginx:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx-main
#networks:
#  nginx-main: